services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/venv  # ไม่ mount venv จาก host
    environment:
      - DATABASE_URL=postgresql://postgres:user@db:5432/Kanban_Board  # แก้ไขช่องว่าง
    depends_on:
      - db
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # รัน uvicorn

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: Kanban_Board
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
